# Generated by Django 4.2.3 on 2023-10-02 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_favoriterecipe_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(
                    1,
                    message='Время приготовления должно быть больше 0.')],
                verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(
                    1,
                    message='Количество ингредиентов в'
                    'рецептедолжно быть больше 0.')],
                verbose_name='Количество'),
        ),
    ]
